name: AndroidBuild
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout

      - name:  Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build With Gradle
        uses: ./gradlew build

      - name: Upload a build artifacts
        uses: actions/upload-artifact@v3.1.3
        with:
          name: CiCd.apk
          path: app/build/outputs/apk/debug/app-debug.apk



